apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    tier: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      type: back-end
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
        type: back-end
    spec:
      containers:
        - name: nginx
          image: nginx
  
  
